"""Payment receipt PDF — school-branded proof of a single payment.

Shows the payment itself plus the invoice position after it (amount, discount,
paid so far, balance, status), so a parent holding the receipt knows exactly
where they stand. A5, pure reportlab.
"""
from io import BytesIO
from reportlab.lib import colors
from reportlab.lib.pagesizes import A5
from reportlab.lib.units import mm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
)


def _brand(hexstr: str | None) -> colors.Color:
    try:
        return colors.HexColor(hexstr)
    except Exception:
        return colors.HexColor("#0B1F3A")


def build_receipt_pdf(data: dict) -> bytes:
    """Expected keys (as passed by the fees router):
    school{name,address,state,color}, receipt_number, student_name,
    admission_number, invoice_number, method, reference, amount, paid_at,
    invoice{amount,discount,paid,balance,status}, received_by (optional).
    """
    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A5,
                            topMargin=12 * mm, bottomMargin=12 * mm,
                            leftMargin=12 * mm, rightMargin=12 * mm)
    brand = _brand(data["school"].get("color"))
    styles = getSampleStyleSheet()
    h_school = ParagraphStyle("school", parent=styles["Title"], fontSize=13,
                              textColor=brand, spaceAfter=1)
    h_sub = ParagraphStyle("sub", parent=styles["Normal"], alignment=1,
                           fontSize=8, textColor=colors.grey)
    h_title = ParagraphStyle("rtitle", parent=styles["Normal"], alignment=1,
                             fontSize=10, spaceBefore=4, spaceAfter=6,
                             textColor=colors.white, backColor=brand)
    small = ParagraphStyle("small", parent=styles["Normal"], fontSize=8)
    story = []

    story.append(Paragraph(data["school"]["name"], h_school))
    addr = " · ".join(x for x in [data["school"].get("address"),
                                  data["school"].get("state")] if x)
    if addr:
        story.append(Paragraph(addr, h_sub))
    story.append(Paragraph("&nbsp;OFFICIAL PAYMENT RECEIPT&nbsp;", h_title))

    method = str(data["method"]).split(".")[-1].upper()
    meta = [
        [Paragraph(f"<b>Receipt No:</b> {data['receipt_number']}", small),
         Paragraph(f"<b>Date:</b> {data['paid_at'] or ''}", small)],
        [Paragraph(f"<b>Student:</b> {data['student_name']}", small),
         Paragraph(f"<b>Admission No:</b> {data['admission_number']}", small)],
        [Paragraph(f"<b>Invoice:</b> {data['invoice_number']}", small),
         Paragraph(f"<b>Method:</b> {method} · Ref: {data['reference']}", small)],
    ]
    mt = Table(meta, colWidths=[62 * mm, 62 * mm])
    mt.setStyle(TableStyle([("BOX", (0, 0), (-1, -1), 0.5, colors.grey),
                            ("INNERGRID", (0, 0), (-1, -1), 0.25, colors.lightgrey),
                            ("TOPPADDING", (0, 0), (-1, -1), 3),
                            ("BOTTOMPADDING", (0, 0), (-1, -1), 3)]))
    story.append(mt)
    story.append(Spacer(1, 8))

    # the payment itself, prominent
    amt = Table([["AMOUNT RECEIVED", f"NGN {data['amount']:,.2f}"]],
                colWidths=[62 * mm, 62 * mm])
    amt.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), brand),
        ("TEXTCOLOR", (0, 0), (-1, -1), colors.white),
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 11),
        ("ALIGN", (1, 0), (1, 0), "RIGHT"),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(amt)
    story.append(Spacer(1, 8))

    inv = data["invoice"]
    status = str(inv["status"]).split(".")[-1].upper()
    totals = [
        ["Invoice amount", f"{inv['amount']:,.2f}"],
        ["Discount", f"{inv['discount']:,.2f}"],
        ["Total paid to date", f"{inv['paid']:,.2f}"],
        ["Outstanding balance", f"{inv['balance']:,.2f}"],
        ["Invoice status", status],
    ]
    tt = Table(totals, colWidths=[70 * mm, 40 * mm])
    tt.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 8.5),
        ("ALIGN", (1, 0), (1, -1), "RIGHT"),
        ("LINEABOVE", (0, 3), (-1, 3), 0.5, brand),
        ("FONTNAME", (0, 3), (-1, -1), "Helvetica-Bold"),
        ("TOPPADDING", (0, 0), (-1, -1), 2.5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2.5),
    ]))
    story.append(tt)
    story.append(Spacer(1, 10))

    if data.get("received_by"):
        story.append(Paragraph(f"Received by: {data['received_by']}", small))
        story.append(Spacer(1, 4))
    story.append(Paragraph(
        "This receipt is system-generated by Fiyox and valid without a signature.",
        h_sub))

    doc.build(story)
    return buf.getvalue()
