"""timetable

Revision ID: 688c0fc7dc0b
Revises: b1c2d3e4f5a6
Create Date: 2026-07-14 15:03:40.623120
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '688c0fc7dc0b'
down_revision: Union[str, None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('periods',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('is_break', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'sequence', name='uq_period_sequence')
    )
    with op.batch_alter_table('periods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_periods_school_id'), ['school_id'], unique=False)

    op.create_table('lessons',
    sa.Column('arm_id', sa.String(length=36), nullable=False),
    sa.Column('day', sa.String(length=10), nullable=False),
    sa.Column('period_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('teacher_id', sa.String(length=36), nullable=True),
    sa.Column('room', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['arm_id'], ['class_arms.id'], ),
    sa.ForeignKeyConstraint(['period_id'], ['periods.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'arm_id', 'day', 'period_id', name='uq_lesson_arm_slot')
    )
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lessons_arm_id'), ['arm_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lessons_day'), ['day'], unique=False)
        batch_op.create_index(batch_op.f('ix_lessons_period_id'), ['period_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lessons_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lessons_teacher_id'), ['teacher_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lessons_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_lessons_school_id'))
        batch_op.drop_index(batch_op.f('ix_lessons_period_id'))
        batch_op.drop_index(batch_op.f('ix_lessons_day'))
        batch_op.drop_index(batch_op.f('ix_lessons_arm_id'))

    op.drop_table('lessons')
    with op.batch_alter_table('periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_periods_school_id'))

    op.drop_table('periods')
    # ### end Alembic commands ###
