"""report card branding and comments

Revision ID: 835a4a67659c
Revises: ede58639faec
Create Date: 2026-07-13 20:50:56.423444
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '835a4a67659c'
down_revision: Union[str, None] = 'ede58639faec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signature_url', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('stamp_url', sa.String(length=400), nullable=True))
        batch_op.add_column(sa.Column('principal_name', sa.String(length=120), nullable=True))

    # NOT NULL columns added to a table that already has rows need a
    # server_default, otherwise Postgres cannot fill the existing rows
    # (Neon rejected this migration in production without it).
    with op.batch_alter_table('term_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_average', sa.Float(),
                                      nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('comments_edited', sa.Boolean(),
                                      nullable=False, server_default=sa.false()))

    # the default was only needed to backfill; new rows get their value from
    # the application, so drop it and keep the schema clean
    with op.batch_alter_table('term_results', schema=None) as batch_op:
        batch_op.alter_column('class_average', server_default=None)
        batch_op.alter_column('comments_edited', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('term_results', schema=None) as batch_op:
        batch_op.drop_column('comments_edited')
        batch_op.drop_column('class_average')

    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_column('principal_name')
        batch_op.drop_column('stamp_url')
        batch_op.drop_column('signature_url')

    # ### end Alembic commands ###
