"""initial schema

Revision ID: a911eb91255f
Revises: 
Create Date: 2026-07-11 01:09:11.610247
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a911eb91255f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('school_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('table_name', sa.String(length=60), nullable=False),
    sa.Column('record_id', sa.String(length=36), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_record_id'), ['record_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_school_id'), ['school_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_table_name'), ['table_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('schools',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('state', sa.String(length=60), nullable=True),
    sa.Column('logo_url', sa.String(length=400), nullable=True),
    sa.Column('primary_color', sa.String(length=9), nullable=False),
    sa.Column('grading_config', sa.JSON(), nullable=False),
    sa.Column('withhold_results_on_debt', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schools_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('school_id', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_id', 'email', name='uq_user_school_email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_school_id'), ['school_id'], unique=False)

    op.create_table('academic_sessions',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('academic_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_academic_sessions_school_id'), ['school_id'], unique=False)

    op.create_table('assessment_components',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('is_exam', sa.Boolean(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assessment_components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assessment_components_school_id'), ['school_id'], unique=False)

    op.create_table('school_classes',
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=10), nullable=False),
    sa.Column('level_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_classes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_classes_school_id'), ['school_id'], unique=False)

    op.create_table('subjects',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=10), nullable=True),
    sa.Column('is_core', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subjects_school_id'), ['school_id'], unique=False)

    op.create_table('class_arms',
    sa.Column('class_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('form_teacher_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], ),
    sa.ForeignKeyConstraint(['form_teacher_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('class_arms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_arms_school_id'), ['school_id'], unique=False)

    op.create_table('terms',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('next_term_begins', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['academic_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_terms_school_id'), ['school_id'], unique=False)

    op.create_table('students',
    sa.Column('admission_number', sa.String(length=40), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('other_names', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('date_admitted', sa.Date(), nullable=True),
    sa.Column('current_arm_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['current_arm_id'], ['class_arms.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_admission_number'), ['admission_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_school_id'), ['school_id'], unique=False)

    op.create_table('teaching_assignments',
    sa.Column('teacher_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('arm_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['arm_id'], ['class_arms.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teaching_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teaching_assignments_school_id'), ['school_id'], unique=False)

    op.create_table('enrollments',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('arm_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['arm_id'], ['class_arms.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['academic_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enrollments_school_id'), ['school_id'], unique=False)

    op.create_table('guardians',
    sa.Column('parent_user_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('relationship', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['parent_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guardians_school_id'), ['school_id'], unique=False)

    op.create_table('score_entries',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('arm_id', sa.String(length=36), nullable=False),
    sa.Column('term_id', sa.String(length=36), nullable=False),
    sa.Column('component_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['arm_id'], ['class_arms.id'], ),
    sa.ForeignKeyConstraint(['component_id'], ['assessment_components.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'subject_id', 'term_id', 'component_id', name='uq_score_unique')
    )
    with op.batch_alter_table('score_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_score_entries_school_id'), ['school_id'], unique=False)

    op.create_table('subject_results',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('subject_id', sa.String(length=36), nullable=False),
    sa.Column('arm_id', sa.String(length=36), nullable=False),
    sa.Column('term_id', sa.String(length=36), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=4), nullable=False),
    sa.Column('remark', sa.String(length=40), nullable=False),
    sa.Column('subject_position', sa.Integer(), nullable=False),
    sa.Column('class_average', sa.Float(), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['arm_id'], ['class_arms.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'subject_id', 'term_id', name='uq_subject_result')
    )
    with op.batch_alter_table('subject_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subject_results_school_id'), ['school_id'], unique=False)

    op.create_table('term_results',
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('arm_id', sa.String(length=36), nullable=False),
    sa.Column('term_id', sa.String(length=36), nullable=False),
    sa.Column('grand_total', sa.Float(), nullable=False),
    sa.Column('average', sa.Float(), nullable=False),
    sa.Column('subjects_count', sa.Integer(), nullable=False),
    sa.Column('class_size', sa.Integer(), nullable=False),
    sa.Column('overall_position', sa.Integer(), nullable=False),
    sa.Column('affective', sa.JSON(), nullable=False),
    sa.Column('form_teacher_comment', sa.String(length=500), nullable=False),
    sa.Column('principal_comment', sa.String(length=500), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['arm_id'], ['class_arms.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'term_id', name='uq_term_result')
    )
    with op.batch_alter_table('term_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_term_results_school_id'), ['school_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('term_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_term_results_school_id'))

    op.drop_table('term_results')
    with op.batch_alter_table('subject_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subject_results_school_id'))

    op.drop_table('subject_results')
    with op.batch_alter_table('score_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_score_entries_school_id'))

    op.drop_table('score_entries')
    with op.batch_alter_table('guardians', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guardians_school_id'))

    op.drop_table('guardians')
    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enrollments_school_id'))

    op.drop_table('enrollments')
    with op.batch_alter_table('teaching_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teaching_assignments_school_id'))

    op.drop_table('teaching_assignments')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_school_id'))
        batch_op.drop_index(batch_op.f('ix_students_admission_number'))

    op.drop_table('students')
    with op.batch_alter_table('terms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_terms_school_id'))

    op.drop_table('terms')
    with op.batch_alter_table('class_arms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_arms_school_id'))

    op.drop_table('class_arms')
    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subjects_school_id'))

    op.drop_table('subjects')
    with op.batch_alter_table('school_classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_classes_school_id'))

    op.drop_table('school_classes')
    with op.batch_alter_table('assessment_components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assessment_components_school_id'))

    op.drop_table('assessment_components')
    with op.batch_alter_table('academic_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_academic_sessions_school_id'))

    op.drop_table('academic_sessions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_school_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('schools', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schools_slug'))

    op.drop_table('schools')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_table_name'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_school_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_record_id'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
