"""notifications message log

Revision ID: ede58639faec
Revises: 1f00ac99d1c1
Create Date: 2026-07-11 10:24:55.704356
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ede58639faec'
down_revision: Union[str, None] = '1f00ac99d1c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_logs',
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('recipient', sa.String(length=120), nullable=False),
    sa.Column('recipient_user_id', sa.String(length=36), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('related_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('provider_ref', sa.String(length=80), nullable=True),
    sa.Column('error', sa.String(length=300), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('school_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('message_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_logs_school_id'), ['school_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_logs_school_id'))

    op.drop_table('message_logs')
    # ### end Alembic commands ###
